# Generated by Django 2.0 on 2018-05-13 15:59

from django.db import migrations
import infotv.models


# Migrate old slides as default decks.
def migrate_data(apps, schema_editor):
    for row in infotv.models.SlideDeck.objects.all():
        old_data = row.data
        if 'slides' in old_data:
            row.data = {
                "decks": {
                    "default": old_data['slides']
                }
            }
            if 'eep' in old_data:
                row.data['eep'] = old_data['eep']
            row.save(update_fields=['data'])


def reverse_data(apps, schema_editor):
    for row in infotv.models.SlideDeck.objects.all():
        old_data = row.data
        if 'decks' in old_data:
            row.data = {
                "slides": old_data['decks']['default']
            }
            if 'eep' in old_data:
                row.data['eep'] = old_data['eep']
            row.save(update_fields=['data'])


class Migration(migrations.Migration):

    dependencies = [
        ('infotv', '0002_eventslugfield'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_code=reverse_data),
    ]
