name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akx/pre-commit-uv-action@v0.1.0
  Python:
    runs-on: ubuntu-latest
    env:
      DEBUG: "1"
    strategy:
      matrix:
        include:
          - python-version: "3.9"
          - python-version: "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "${{ matrix.python-version }}"
      - run: uvx --with=tox-gh-actions --with=tox-uv tox
      - uses: codecov/codecov-action@v5
  JavaScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: |
            infotv/frontend/package.json
            infotv/frontend/yarn.lock
      - run: yarn --frozen-lockfile
        working-directory: ./infotv/frontend
      - run: yarn lint
        working-directory: ./infotv/frontend
      - run: yarn build
        working-directory: ./infotv/frontend
      - run: yarn test
        working-directory: ./infotv/frontend
      - uses: actions/upload-artifact@v4
        with:
          name: infotv-static
          path: ./infotv/static

  Build-Wheel:
    needs:
      - JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - uses: actions/download-artifact@v4
        with:
          name: infotv-static
          path: infotv/static
      - run: uv build .
      - run: zipinfo dist/*.whl | grep static/infotv/bundle.js || exit 42
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
