name: CI
"on":
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
  Python:
    runs-on: ubuntu-latest
    env:
      DEBUG: "1"
    strategy:
      matrix:
        include:
          - python-version: "3.9"
          - python-version: "3.13"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "${{ matrix.python-version }}"
      - run: uvx --with=tox-gh-actions --with=tox-uv tox
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
  JavaScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: |
            infotv/frontend/package.json
            infotv/frontend/yarn.lock
      - run: yarn --frozen-lockfile
        working-directory: ./infotv/frontend
      - run: yarn lint
        working-directory: ./infotv/frontend
      - run: yarn build
        working-directory: ./infotv/frontend
      - run: yarn test
        working-directory: ./infotv/frontend
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: infotv-static
          path: ./infotv/static

  Build-Wheel:
    needs:
      - JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: "3.13"
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: infotv-static
          path: infotv/static
      - run: uv build .
      - run: zipinfo dist/*.whl | grep static/infotv/bundle.js || exit 42
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist

  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - Build-Wheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist
      - run: gh release create "$GITHUB_REF_NAME" dist/*.whl --title "$GITHUB_REF_NAME" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
